### ISSUE TITLE
Error in open.connection(file, "rt") :    cannot open the connection to 'http://www.statistica.it/gianluca/bmeta/Data-bin.csv'

### ISSUE THREAD

**Issue by leeson89** [giabaio/bmeta#1]
Error in open.connection(file, "rt") : 
  cannot open the connection to 'http://www.statistica.it/gianluca/bmeta/Data-bin.csv'
Warning message:
In c(x, values) :
  closing unused connection 3 (http://www.statistica.it/gianluca/bmeta/Data-bin.csv)

**Comment by giabaio** [comment]
The URLs are for an old version of my website, so they won't work now. I've added them back to the new version and the correct URLs are
1. [https://gianluca.statistica.it/software/bmeta/Data-bin.csv](https://gianluca.statistica.it/software/bmeta/Data-bin.csv)
2. [https://gianluca.statistica.it/software/bmeta/Data-count.csv](https://gianluca.statistica.it/software/bmeta/Data-count.csv)
3. [https://gianluca.statistica.it/software/bmeta/Data-ctns.csv](https://gianluca.statistica.it/software/bmeta/Data-ctns.csv)

The website should update in a minute and then you could use the relevant files (**pointing it to the new URLs!**).

**Comment by giabaio** [comment]
The latest version does address and fix these issues!
